# This file is managed by bootstrap. DO NOT edit this file directly.

# taps
tap 'antoniorodr/memo'
tap 'gastownhall/gascity'
tap 'hamed-elfayome/claude-usage'

# formula
brew 'antoniorodr/memo/memo'
brew 'ccusage'
brew 'container'
brew 'coreutils'
brew 'direnv'
brew 'gastown'
brew 'gastownhall/gascity/gascity'
brew 'git'
brew 'jq'
brew 'kube-ps1'
brew 'stow'
brew 'tilt'
brew 'tmux'
brew 'tree'
brew 'watch'
brew 'wget'
brew 'zsh-autosuggestions'
brew 'zsh-history-substring-search'
brew 'zsh-syntax-highlighting'

# casks
cask '1password', greedy: false
cask 'antigravity-cli', greedy: false
cask 'claude', greedy: false
cask 'claude-code', greedy: false
cask 'claudebar', greedy: false
cask 'hamed-elfayome/claude-usage/claude-usage-tracker', greedy: false
cask 'intellij-idea', greedy: false
cask 'iterm2', greedy: false
cask 'visual-studio-code', greedy: false
