# This file is managed by bootstrap. DO NOT edit this file directly.

# taps
tap 'hamed-elfayome/claude-usage'

# formula
brew 'ccusage'
brew 'coreutils'
brew 'direnv'
brew 'gastown'
brew 'git'
brew 'jq'
brew 'kube-ps1'
brew 'tilt'
brew 'tmux'
brew 'tree'
brew 'watch'
brew 'wget'
brew 'zsh-autosuggestions'
brew 'zsh-history-substring-search'
brew 'zsh-syntax-highlighting'

# casks
cask '1password', greedy: false
cask '1password-cli', greedy: false
cask 'claude-code', greedy: false
cask 'hamed-elfayome/claude-usage/claude-usage-tracker', greedy: false
cask 'docker-desktop', greedy: false
cask 'intellij-idea', greedy: false
cask 'iterm2', greedy: false
cask 'visual-studio-code', greedy: false
