global
    maxconn 256
    pidfile /usr/local/var/run/haproxy.pid
    log 127.0.0.1 local0
    log 127.0.0.1 local1 notice

defaults
    log global
    mode http
    retries 3
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms
    option forwardfor
    option httpclose
    option httplog
    stats enable

frontend http-in
    bind :80
    bind :89 accept-proxy
    default_backend web
    acl camera_url hdr_beg(host) -i camera
    use_backend camera if camera_url
    acl denon_url hdr_beg(host) -i denon
    use_backend denon if denon_url

backend camera
    acl secure dst_port 443
    reqirep ^Host: Host:\ 192.168.1.91
    redirect prefix http://camera.ungboriboonpisal.com if secure
    server camera1 192.168.1.91 maxconn 32

backend denon
    acl secure dst_port 443
    redirect prefix http://denon.ungboriboonpisal.com if secure
    server denon1 192.168.1.96 maxconn 32

backend web
    server web1 127.0.0.1:8088 maxconn 32
    
