syntax on
filetype on
filetype plugin on
set ruler
set number
set softtabstop=2
set tabstop=2
set shiftwidth=2
set expandtab
set smartindent
set cursorline
set background=dark

" Allow saving of files as sudo when I forgot to start vim using sudo.
cmap w!! %!sudo tee > /dev/null %

