set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'fatih/vim-go'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-sleuth'
Plugin 'fatih/molokai'

call vundle#end()
filetype plugin indent on

set ruler
set number
set expandtab
set softtabstop=2
set tabstop=2
set shiftwidth=2
set autoindent
set cursorline
set backspace=indent,eol,start
set re=0

" Allow saving of files as sudo when I forgot to start vim using sudo.
cmap w!! %!sudo tee > /dev/null %

syntax on
silent! colorscheme molokai

let g:ycm_server_keep_logfiles = 1

autocmd BufWritePre * :%s/\s\+$//e
